name: calendar
description: A Clean Project created by EB Clean CLI.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #router
  auto_route: ^7.8.0

  #intl
  intl: ^0.18.1

  #env
  envied: ^0.3.0+3

  #dependency injection
  get_it: ^7.6.0
  injectable: ^2.3.0

  #state management
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

  #flutter hooks
  flutter_hooks: ^0.20.0

  #adaptive sizes
  adaptive_sizer:
    git:
      url: https://github.com/kishor98100/adaptive_sizer

  #data models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  #functional programmings
  fpdart: ^1.1.0

  #network requests
  dio: ^5.3.2
  gql_dio_link: ^1.0.1
  ferry: ^0.14.2+1

  #Session
  hive_local_storage: ^1.0.6

  #logger
  logger: ^2.0.1

  #path_provider
  path_provider: ^2.0.13

  #google fonts
  google_fonts: ^5.1.0

  #native splash
  flutter_native_splash: ^2.3.2

  #image and svg renderer
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7

  #device info plus
  device_info_plus: ^9.0.3

  #calendar
  table_calendar: ^3.0.8
  month_picker_dialog: ^2.0.0

  #from field validator
  form_field_validator: ^1.1.0

  #animation
  flutter_animate: ^4.1.1+1

  remixicon: ^1.0.0

  #google
  google_sign_in: ^6.1.4
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1

  #flutter slidable
  flutter_slidable: ^3.0.0

  #eb
  eb_core_flutter:
    git:
      url: git@bitbucket.org:ebpearls28/eb_core_flutter.git
      ref: v0.0.4

  #firebase
  firebase_core: ^2.15.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

  #generators
  build_runner: ^2.4.6

  json_serializable: ^6.7.1
  freezed: ^2.4.1
  hive_generator: ^2.0.0

  injectable_generator: ^2.4.0

  #route generator
  auto_route_generator: ^7.3.1

  # erry generator
  ferry_generator: ^0.8.1

  #test packages
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

  #launcher icons
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.3.0+3

  #assets
  flutter_gen_runner: ^5.3.2

dependency_overrides:
  path: ^1.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - google_fonts/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/localization/arb
  output_dir: lib/localization/generated

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    image: assets/images/splash_12.png
    icon_background_color: "#FFFFFF"

#flutter asset generator
flutter_gen:
  output: lib/gen/
