import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive_flutter/hive_flutter.dart';

/// required: associates our `product_model.dart` with the code generated by Freezed
part 'user_model.freezed.dart';

/// optional: Since our Person class is serializable, we must add this line.
/// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel extends HiveObject with _$UserModel {
  UserModel._();

  @HiveType(typeId: 3)
  factory UserModel({
    @HiveField(0) @Default('-') String id,
    @HiveField(1) @Default('-') String firstName,
    @HiveField(2) @Default('-') String lastName,
    @HiveField(3) @Default('-') String email,
    @HiveField(4) @Default('-') String address,
    @HiveField(5) @Default('-') String phoneNumber,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);
}
